### ISSUE TITLE
Support for temporary and RHS variables in attributeConstraints

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-gt-ui-pattern#10]
Inside 'attributeConstraints', we would like to have temporary and RHS variables.
For instance, the EClass Node has a label attribute of type EString.
If we want to add a prefix to the label of the object variable 'this' of type 'Node', we need (i) a temporary variable and (ii) a way to refer to RHS variables. In the old constraints-specification language, this was possible by adding a prime the variable name (e.g., ````eq(this.label', "New label")```).
```
this : Node
attributeConstraints {
  concat_String(tmp_label, "prefix", this.label)
  eq_String(this.label', tmp_label)
}
```

**Comment by SaschaEdwinZander** [comment]
done
