### ISSUE TITLE
Wizard: Create MPT & MCF File

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon-gt-ui-pattern#6]
Create a wizard for the creating an MPT and MCF file (for a specific Ecore file).

Basic version: Just create two files for a given 'basename' (e.g., 'DoubleLinkedList' -> 'DoubleLinkedList.mcf' + 'DoubleLinkedList.mpt') and add the necessary 'import' statement to the MCF file.
Improved version: Let the user choose from the set of Ecore files in the workspace and create some template content (e.g., appropriate import,...).

**Comment by SaschaEdwinZander** [comment]
done
